spring:
  datasource:
    url: jdbc:postgresql://localhost/somanyfeeds
    username: somanyfeeds
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

banner:
  location: classpath:banner.txt
